Fix unknown attribute error in cryptography
If someone runs cryptography 1.0<=x<1.5 it will run into this error:
  '_EllipticCurvePublicKey' object has no attribute 'verify'

This interface has been introduced in:
  https://github.com/pyca/cryptography/commit/2120a8e090ff8974d727f76aae5f2f9eac56656c

It is available in 1.5

Signed-off-by: Arthur Gautier <baloo@gandi.net>